-- Generated from rubric.txt by scripts/seed-rubric.ts. Do not edit by hand.
delete from public.rubric_criteria;
insert into public.rubric_criteria (role, criterion_number, criterion_name, description, weight) values
  ('PM', 1, 'Shipment-level operations experience', 'Has held at least one role in which they personally handled shipment-level work. The CV names specific artefacts or processes (e.g. Bills of Lading, shipping bills, carrier allocation, DO release, customs clearance, delivery exception handling) AND states a volume or account count (e.g. "180+ shipments monthly", "12 key accounts"). Exposure only through building, selling or integrating software for logistics companies does not count. Statements of familiarity, passion or curiosity about logistics do not count.', 35),
  ('PM', 2, 'Names the broken workflow step it fixed', 'One bullet, or adjacent bullets within the same role, contains all three of the following: (1) a problem named as a specific step in a specific group''s work, precise enough that a reviewer could say who performs the step and what goes wrong in it; (2) what the candidate did about it; (3) a result stated as a change in what those people did (usage, support tickets, time taken, adoption count, or the process being retained). Generic wording such as "friction points", "pain points", "user needs", "insights" or "improved the workflow" without a named step does not qualify. Results stated only as system metrics (latency, uptime, query time) do not qualify. Reviewer test: could you draw the broken step from the bullet alone?', 20),
  ('PM', 3, 'Unassigned fixes that others adopted', 'At least one tool, process or artefact the candidate created that was outside the remit of the role they held at the time, with stated evidence that other people adopted it without being mandated to. The evidence names a team, a count or a timeframe (e.g. "adopted by 2 other regional teams", "12-member team within two weeks", "now used by the full sales team"). Initiatives that fall within what the role was hired to do (e.g. a PM writing PM templates, a marketer producing case studies) do not qualify. Things built with no stated users do not qualify.', 25),
  ('PM', 4, 'Carries breakdowns through to the affected party', 'Describes a specific incident, failure, lost deal or killed initiative; states what the candidate personally did; AND states either how they communicated with the affected customer or team, or what changed afterwards so it would not recur. A CV containing only wins does not qualify. Incident handling shown only as an assigned technical fix (e.g. "part of the on-call rotation") with no communication or process follow-through does not qualify.', 20),
  ('SPM', 1, 'Shipment-level operations experience', 'Has held at least one role in which they personally handled shipment-level work, with named artefacts or processes (e.g. Bills of Lading, shipping bills, carrier allocation, DO release, customs clearance, delivery exception handling) AND a stated volume or account count. In addition, the role involved coordinating handoffs across at least three named external party types (e.g. shipping lines, CHAs, port authorities, customs or DGFT, carriers, client ERP or finance teams). Operations work confined to one party''s internal process does not meet this bar. Exposure only through building, selling or integrating software for logistics companies does not count.', 25),
  ('SPM', 2, 'Names the broken workflow step it fixed', 'One bullet, or adjacent bullets within the same role, contains all three of the following: (1) a problem named as a specific step in a specific group''s work, precise enough that a reviewer could say who performs the step and what goes wrong in it; (2) what the candidate did about it; (3) a result stated as a change in what those people did. In addition, the fix was applied beyond a single account or team, with a stated count or scope (e.g. "now a core platform feature", "reduced integration timelines for new customers"), and the CV shows the candidate made the build or don''t-build call themselves. A single-account or single-feature fix does not meet this bar. Generic wording without a named step does not qualify.', 20),
  ('SPM', 3, 'Unassigned fixes that others adopted', 'Two or more separate instances of a tool, process or artefact the candidate created outside the remit of the role they held at the time, each with stated evidence of voluntary adoption (a named team, count or timeframe). At least one instance spread beyond the candidate''s own team or function, or became a permanent standard. A single instance does not meet this bar. Initiatives within the role''s assigned remit do not qualify.', 25),
  ('SPM', 4, 'Carries breakdowns through to the affected party', 'Describes a specific incident, failure, lost deal or killed initiative that resulted from the candidate''s own decision; states what the candidate personally did; states how they communicated with the affected customer or team; AND states that the follow-through became a team-wide standard or practice (e.g. "now standard practice before account qualification", "owned the follow-up action items to closure", "reduced P1 incidents by 40%"). Breakdowns the candidate handled but did not cause, or that produced no lasting team standard, do not meet this bar. A CV containing only wins does not qualify.', 30);
